src/store/slices/characters.ts
=> Some items refuse to equip

src/encounters/chest.ts, src/equipment/equipItemPrompt.ts
=> Chest shows items twice

src/commands/inspect/getHook.ts, src/commands/inventory.ts
=> Inventory threads

src/character/getStatusEffectStatModifier.ts
=> Status effects not expiring properly

src/character/Character.ts, src/store/slices/characters.ts
=> Status effects are not being purged

src/character/cooldowns/cooldownRemainingText.ts, src/character/cooldowns/getCooldownRemaining.ts, src/character/isCharacterOnCooldown.ts, src/commands/adventure.ts, src/commands/attack.ts, src/commands/heal.ts, src/commands/inspect/actionEmbed.ts, src/commands/renew.ts, src/index.ts
=> Cooldowns are reported inconsistently

.gitignore, src/index.ts
=> Memoize installCommands to avoid unnecessary updates.

src/encounters/shrine/armor.ts, src/encounters/shrine/attack.ts, src/encounters/shrine/slayer.ts, src/encounters/shrine/vigor.ts, src/encounters/tavern/restfulNight.ts, src/equipment/equipment.ts, src/equipment/items/index.ts, src/equipment/items/unidentifiedPotion.ts, src/equipment/randomChestItem.ts, src/equipment/useInventoryItemPrompt.ts, src/statusEffects/StatusEffect.ts, src/statusEffects/createEffect.ts, src/statusEffects/index.ts, src/statusEffects/templates/TemplateEffect.ts, src/statusEffects/templates/aggression.ts, src/statusEffects/templates/frailty.ts, src/statusEffects/templates/index.ts, src/statusEffects/templates/invigorated.ts, src/statusEffects/templates/protectedEffect.ts, src/statusEffects/templates/slayer.ts, src/utils/getAsset.ts
=> Unidentifed potions

src/character/loot/loot.ts, src/commands/admin/lootme.ts, src/commands/admin/lootmonster.ts, src/commands/attack.ts, src/encounters/monster.ts
=> Crown Win Condition

src/commands/admin/admin.ts, src/index.ts, src/store/actions/index.ts, src/store/actions/newGame.ts, src/store/slices/characters.ts, src/store/slices/encounters.ts, src/store/slices/loots.ts
=> Server tick

src/commands/inspect/getHook.ts, src/commands/list/listMonsters.ts, src/monster/monsterEmbed.ts
=> `/list monsters` should output a thread

developer-guide.md, src/commands/index.ts, src/index.ts
=> Improve misconfiguration feedback

packages/game/src/attack/makeAttack.ts
=> Combat log shows incorrect values

packages/game/src/encounters/shop/sellItemPrompt.ts, packages/game/src/encounters/shop/shop.ts
=> Attempting to sell with too many items results in error

packages/game/src/commands/set.ts
=> Ensure character exists before setting profile

packages/game/src/character/list/listCharacters.ts
=> Character thread auto-archive results in crash

packages/game/src/encounters/travel.ts, packages/game/src/equipment/items/index.ts, packages/game/src/equipment/items/travelersRing.ts
=> Traveler's ring

packages/game/src/encounters/monster.ts
=> Defeating a monster displays outdated quest progress

packages/game/src/encounters/monster.ts
=> Killed enemy indicated no Slayer progress

packages/game/src/Emoji.ts, packages/game/src/attack/AttackResult.ts, packages/game/src/attack/makeAttack.ts, packages/game/src/boot.ts, packages/game/src/character/Stats.ts, packages/game/src/character/defaultCharacter.ts, packages/game/src/character/getCharacterStatModified.ts, packages/game/src/character/statsEmbed.ts, packages/game/src/commands/admin/item.ts, packages/game/src/commands/buyItem.ts, packages/game/src/crown/announceItemsReceived.ts, packages/game/src/encounters/chest.ts, packages/game/src/encounters/monster.ts, packages/game/src/equipment/items/index.ts, packages/game/src/equipment/items/swordOfDragonSlaying.ts, packages/game/src/store/actions/index.ts, packages/game/src/store/selectors/index.ts, packages/game/src/utils/dice.ts
Dragons have a chance to drop a Sword of Dragon Slaying.
=> Sword of Dragon Slaying

packages/game/src/commands/admin/encounter.ts, packages/game/src/encounters/index.ts, packages/game/src/encounters/shrine/shrineEmbeds.ts, packages/game/src/encounters/tavern/restfulNight.ts, packages/game/src/encounters/travel.ts
Remove now-duplicate status notifications
https://github.com/Adventure-Bot/adventure-bot/blob/76a5cb04d33a55c7e47e2591b7da59bb99b514c3/packages/game/src/announcements/announceEffectAdded.ts#L13
=> Remove duplicate effect announcements

packages/game/src/announcements/announceLoots.ts, packages/game/src/announcements/declareGameWon.ts, packages/game/src/announcements/index.ts, packages/game/src/attack/makeAttack.ts, packages/game/src/boot.ts, packages/game/src/character/index.ts, packages/game/src/character/inventoryFields.ts, packages/game/src/character/loot/loot.ts, packages/game/src/commands/admin/lootme.ts, packages/game/src/commands/admin/lootmonster.ts, packages/game/src/commands/attack.ts, packages/game/src/encounters/monster.ts, packages/game/src/index.ts, packages/game/src/store/slices/characters.ts, packages/game/src/store/slices/crown.ts, packages/game/src/store/slices/loots.ts
Loot announcements happen implicitly per new announce loots
https://github.com/Adventure-Bot/adventure-bot/pull/180/files#diff-4df4bf085630f0df07086e6f5a1a87d9eaae2075c985aa53fd6b050976000891R107
=> Generalized loot announcements

packages/game/src/announcements/announceItemsReceived.ts, packages/game/src/announcements/announceLoots.ts, packages/game/src/commands/buyItem.ts, packages/game/src/commands/inspect/inspect.ts, packages/game/src/commands/inventory.ts, packages/game/src/encounters/shop/shop.ts, packages/game/src/equipment/equipItemPrompt.ts, packages/game/src/equipment/itemEmbed.ts, packages/game/src/equipment/offerItemPrompt.ts, packages/game/src/store/index.ts, packages/game/src/store/reducers.ts, packages/game/src/store/slices/shop.ts
Shops now remove items from stock when purchased, restock on visit.
=> Shop stock

packages/game/src/attack/embed/attackResultEmbedCompact.ts, packages/game/src/encounters/encounterEmbed.ts, packages/game/src/encounters/monster.ts
Get rid of combat logs (don't think anyone uses them), show attack rolls in the compact view.
=> Simplified monster view

packages/game/src/store/slices/characters.ts, packages/game/src/store/slices/shop.ts
=> Purchasing items should result in item being added to inventory, and gold deducted

packages/game/src/encounters/chest/chest.ts, packages/game/src/leaderboard/leaderboardEmbeds.ts, packages/game/src/leaderboard/renderLeaderboard.ts, packages/game/src/store/selectors/index.ts, packages/game/src/store/slices/crown.ts
=> Crown bearer listed on #leaderboard

packages/game/src/Emoji.ts, packages/game/src/announcements/announceStatContested.ts, packages/game/src/announcements/index.ts, packages/game/src/boot/setupGuild.ts, packages/game/src/character/index.ts, packages/game/src/character/statContest.ts, packages/game/src/encounters/chest/chest.ts, packages/game/src/encounters/chest/chestEmbed.ts
Generic stat contest functionality and implementation within chest.
=> Stat Contest - Chest

packages/game/src/announcements/announceTrapAttacked.ts, packages/game/src/announcements/announceXpAwarded.ts, packages/game/src/character/awardXP.ts, packages/game/src/encounters/chest/chest.ts, packages/game/src/encounters/fairyWell.ts, packages/game/src/encounters/shrine/Shrine.ts, packages/game/src/encounters/shrine/applyShrine.ts, packages/game/src/encounters/shrine/vigor.ts, packages/game/src/encounters/tavern/chattyTavernkeepers.ts, packages/game/src/encounters/tavern/restfulNight.ts, packages/game/src/encounters/travel.ts, packages/game/src/store/slices/characters.ts
XP awarded notifications are now associated with their source message.
=> awardXP message context

packages/game/src/utils/asset.ts
=> Encode asset urls

packages/game/src/announcements/announceEffectAdded.ts, packages/game/src/announcements/announceHealed.ts, packages/game/src/announcements/announceXpAwarded.ts, packages/game/src/announcements/index.ts, packages/game/src/boot/setupGuild.ts, packages/game/src/character/awardXP.ts, packages/game/src/character/hpBar/hpBarField.ts, packages/game/src/commands/admin/effect.ts, packages/game/src/commands/heal.ts, packages/game/src/encounters/chest/chest.ts, packages/game/src/encounters/fairyWell.ts, packages/game/src/encounters/shrine/applyShrine.ts, packages/game/src/encounters/tavern/chattyTavernkeepers.ts, packages/game/src/encounters/tavern/restfulNight.ts, packages/game/src/encounters/travel.ts, packages/game/src/equipment/useInventoryItemPrompt.ts, packages/game/src/quest/rewards/buffQuestReward.ts, packages/game/src/store/slices/characters.ts, packages/game/src/store/slices/statusEffects.ts, packages/game/src/trap/trapAttack.ts
More consistent standalone healing announcements
=> Healing announcements

packages/game/src/announcements/announceCooldowns.ts, packages/game/src/encounters/shop/buyList.ts, packages/game/src/encounters/shop/sellList.ts, packages/game/src/equipment/itemSelect.ts, packages/game/src/utils/index.ts
Also, don't announce cooldowns if they're disabled
=> truncate shop descriptions to prevent going over Discord limits

packages/game/src/announcements/announceCooldowns.ts, packages/game/src/attack/playerAttack.ts, packages/game/src/character/startCooldown.ts, packages/game/src/commands/adventure.ts, packages/game/src/commands/heal.ts, packages/game/src/heal/heal.ts, packages/game/src/store/slices/characters.ts
Cooldown reminder has convenient emoji to activate the ability again.
=> Announce cooldown emoji prompt

packages/game/src/Emoji.ts, packages/game/src/announcements/announceEffectRemoved.ts, packages/game/src/announcements/index.ts, packages/game/src/boot/setupGuild.ts, packages/game/src/encounters/fairyWell.ts, packages/game/src/store/slices/statusEffects.ts
=> Fairy well removes a debuff if you have one

packages/game/src/announcements/announceGoldStolen.ts, packages/game/src/encounters/thugs.ts, packages/game/src/store/slices/characters.ts
Thugs can no longer put you in debt. Kneecaps rejoice.
Worn items will no longer fall to the floor, only items in your backpack.
=> fix: Thugs cannot take more gold than a player has, nor items worn

packages/game/src/encounters/shop/sellItemPrompt.ts, packages/game/src/encounters/shop/sellList.ts
=> Sell list shows whether item is equipped

packages/game/src/announcements/announceHealed.ts, packages/game/src/commands/heal.ts, packages/game/src/encounters/fairyWell.ts, packages/game/src/heal/HealResult.ts, packages/game/src/heal/healAbility.ts
=> Don't announce negative healing, prevent overhealing with heal ability
